#!/usr/bin/env bash
# Transfers a file from the client to the server using SCP with strict host key checking disabled

if [[ "$#" -ne 4 ]]; then
  printf "Usage: %s PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY\n" "$(basename "$0")"
  exit 1
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

scp -i "$ssh_key_path" -o StrictHostKeyChecking=no "$file_path" "$username@$server_ip:~/"
